CREATE DATABASE bbs CHARACTER SET utf8;

USE bbs;

CREATE TABLE `entry` (
  `id`            MEDIUMINT   NOT NULL AUTO_INCREMENT,
  `name`          TEXT        NOT NULL, 
  `body`        MEDIUMTEXT  NOT NULL, 
  `timestamp`     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
